---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo-prod
  namespace: prod
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.4
spec:
  releaseName: podinfo-prod
  chart:
    git: git@github.com:yousseph/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image: youssefgh/podinfo:0.4.10
    replicaCount: 3
